name: DEBUG show secrets

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    environment: test_env
    steps:
      - name: DEBUG Output
        shell: bash
        run: |
          echo TEST_SECRET "${{secrets.TEST_SECRET }}" | sed 's/./& /g'
